baseURL = "https://docs.maxlab.io/"
title = "MAXLAB.IO | Canadian Computer Vision Company"
enableRobotsTXT = true

# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
# theme = ["github.com/onweru/compose"] # edit this if you'ld rather use a fork of this repo

theme = "compose"
enableGitInfo = true

[params]
gtag_id = "G-VL8YF5QWS1"

# disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "RSS","JSON"]

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5
